export const USER_INFO = 'USER_INFO'
export const USER_INFO_FAILED = 'USER_INFO_FAILED'
export const USER_INFO_UPDATED = 'USER_INFO_UPDATED'

export const USER_INFO_REQUESTED = 'USER_INFO_REQUESTED'
export const USER_INFO_UPDATED_REQUESTED = 'USER_INFO_UPDATED_REQUESTED'